### ISSUE TITLE
Remove / edit activities from HOME screen

### ISSUE THREAD

**Issue by PhilGrunewald** [PhilGrunewald/MeterApp#5]
Left symbol to remove
Right time (when reported) - onClick option to change the time

**Comment by PhilGrunewald** [comment]
Information to display on HOME screen:

---

### Ongoing activities

`remove me` activity - location symbol - time

### Past activities

`reactivate me` - activity - location symbol - end time

---

Functionality:
`<remove me>`
OnClick: move to "Past activities"

`<reactivate me>`
OnClick: add to "Ongoing activities" with current time

`<activity> <location symbol> <time>`
OnClick: edit location and time

**Comment by PhilGrunewald** [comment]
once a long list of activities had piled up (>240 entries), the app 'froze' on 'enjoyment' - failed to build the 'home' screen.

I trust this will go away if the activity list is kept to a reasonable length.

**Comment by gozzilli** [comment]
Given that this generates problems, it should be high priority. 
@PhilGrunewald you are assigned to it so I'll leave it to you. Let me know if you want me to chip in (it's probably a big-ish piece of code.

**Comment by gozzilli** [comment]
Why don't I keep my mouth shut?

**Comment by PhilGrunewald** [comment]
Be my guest - the 'remove' function isn't working yet (I don't think) and I am not sure if I can hard code the 'item' as a reference into the html tag...

**Comment by gozzilli** [comment]
Ok, I'll have a look.

**Comment by gozzilli** [comment]
COMPLETE/REMOVE activity is now implemented. 
We're not currently (afaik) keeping a list of past activities, as per your diagram above. Should we?

**Comment by gozzilli** [comment]
Also I should add that to implement this I've used a UUID for storing the key of a newly created activity. This changes the structure of `activity_list` from array to dictionary (well, just object in JS). I haven't checked thoroughly if this breaks anything (I'm thinking of the logging mainly).

**Comment by gozzilli** [comment]
I've added time to the activity list. This is a fairly major restructuing of both the layout of the activity list and the storage of the activity list in the `localStorage` object. 

The activity list is now a dictionary with key `UUID` (this was such already), but with value an object containing (so far) `name` and `time`. This can be extended and it's much more robust. It's also a necessary change to save the time of an activity. 

Here is the structure:

```
activityList[uuid] = {
  "name" : app.get(CURR_ACTIVITY),
  "time" : Date.now()
}
```

And here is what it looks like:
![meter2](https://cloud.githubusercontent.com/assets/1502267/14022920/e37d5c80-f1d9-11e5-80fe-437a1d28fd1a.png)

Since this could be fairly disruptive, I've put it in a separate branch `done-time`. @PhilGrunewald please merge this (or let me know and I'll merge it) before doing much more development. 

Also, please let me know if it disrupted any other function that you have implemented.

**Comment by PhilGrunewald** [comment]
You are a star.
Thank you so much.
If you don't mind, I'll play with it over easter...
Phil

-------- Original message --------
