### ISSUE TITLE
Button size on Android

### ISSUE THREAD

**Issue by PhilGrunewald** [PhilGrunewald/MeterApp#6]
Buttons have small / varying height

**Comment by gozzilli** [comment]
The cause of this bug is the lack of support for CSS viewport units in Android WebView (although canisue states the opposite: http://caniuse.com/#feat=viewport-units).

Two possible solutions:
- we use other units (percentage)
- we use crosswalk, which gives us a full chrome webview. I've tested it and it works. Problems is it makes the APK 18MB bigger. 

I suggest that for now we do neither and see later down the line if we need a full chrome webview. If not, we should just switch units.
